export const EDUCATION_SYSTEMS = {
  IB: {
    name: 'International Baccalaureate',
    programs: {
      IBDP: {
        name: 'IB Diploma Programme (IBDP)',
        subjectGroups: {
          'Group 1: Studies in Language and Literature': [
            'Language A: Literature',
            'Language A: Language & Literature',
            'Literature & Performance',
          ],
          'Group 2: Language Acquisition': [
            'Language B',
            'Language ab initio',
            'Latin',
            'Classical Greek',
          ],
          'Group 3: Individuals and Societies': [
            'Business Management',
            'Economics',
            'Geography',
            'Global Politics',
            'History',
            'Digital Society',
            'Philosophy',
            'Psychology',
            'Social & Cultural Anthropology',
            'World Religions',
          ],
          'Group 4: Sciences': [
            'Biology',
            'Chemistry',
            'Physics',
            'Computer Science',
            'Design Technology',
            'Sports, Exercise & Health Science',
            'Environmental Systems & Societies',
          ],
          'Group 5: Mathematics': [
            'Mathematics: Analysis & Approaches',
            'Mathematics: Applications & Interpretation',
          ],
          'Group 6: The Arts': [
            'Dance',
            'Film',
            'Music',
            'Theatre',
            'Visual Arts',
          ],
        },
        requirements: 'Students must select 6 subjects (one from each group, or replace Group 6 with another from Groups 1-4). Must take 3-4 subjects at HL and rest at SL.',
        grading: {
          scale: [1, 2, 3, 4, 5, 6, 7],
          passing: 4,
          description: '7 is highest, 1 is lowest. Maximum 45 points total (42 from subjects + 3 from TOK/EE).',
        },
      },
      IBCP: {
        name: 'IB Career-related Programme (IBCP)',
        requirements: 'Select minimum 2 DP courses (HL or SL) from any subject group + Career-related Study + CP Core',
        subjectGroups: 'Same subjects as IBDP (any 2+ DP courses)',
        grading: {
          scale: [1, 2, 3, 4, 5, 6, 7],
          passing: 4,
          description: '7 is highest, 1 is lowest for DP courses.',
        },
      },
      'IB Courses': {
        name: 'Individual IB Courses (MYP/Other)',
        subjects: [
          'IB Biology',
          'IB Chemistry',
          'IB Physics',
          'IB Mathematics',
          'IB English',
          'IB History',
          'IB Economics',
          'IB Psychology',
          'IB Computer Science',
          'IB Visual Arts',
        ],
        grading: {
          scale: [1, 2, 3, 4, 5, 6, 7],
          passing: 4,
          description: '7 is highest, 1 is lowest.',
        },
      },
    },
  },
  'A-Level': {
    name: 'A-Level (UK/Cambridge)',
    programs: {
      'A-Level': {
        name: 'A-Level',
        subjects: [
          // Mathematics
          'Mathematics',
          'Further Mathematics',
          'Statistics',

          // Sciences
          'Biology',
          'Chemistry',
          'Physics',
          'Geology',
          'Environmental Science',

          // English
          'English Language',
          'English Literature',
          'English Language & Literature',

          // Humanities & Social Sciences
          'History',
          'Geography',
          'Economics',
          'Business',
          'Politics',
          'Government & Politics',
          'Law',
          'Psychology',
          'Sociology',
          'Religious Studies',
          'Philosophy & Ethics',

          // Languages
          'French',
          'German',
          'Spanish',
          'Italian',
          'Russian',
          'Chinese',
          'Japanese',
          'Arabic',
          'Urdu',
          'Polish',
          'Portuguese',
          'Turkish',
          'Modern Hebrew',
          'Latin',
          'Classical Greek',

          // Creative & Performing Arts
          'Art & Design',
          'Fine Art',
          'Graphic Communication',
          'Photography',
          'Textile Design',
          '3D Design',
          'Drama & Theatre',
          'Music',
          'Music Technology',
          'Film Studies',
          'Media Studies',
          'Dance',

          // Technology, Computing, PE
          'Design & Technology',
          'Computer Science',
          'Physical Education',

          // Cambridge International extras
          'Marine Science',
          'Global Perspectives & Research',
          'Thinking Skills',
          'English General Paper',
          'Information Technology',
          'Travel & Tourism',
          'Classical Studies',
        ],
        requirements: 'Students typically take 3-4 A-Levels',
        grading: {
          scale: ['A*', 'A', 'B', 'C', 'D', 'E', 'U'],
          passing: 'E',
          description: 'A* is highest, E is minimum pass, U is ungraded/fail',
        },
      },
    },
  },
  American: {
    name: 'American High School',
    programs: {
      'Standard': {
        name: 'Standard Courses',
        subjects: [
          // Mathematics
          'Algebra I',
          'Algebra II',
          'Geometry',
          'Precalculus',
          'Calculus',
          'Statistics',

          // Science
          'Biology',
          'Chemistry',
          'Physics',
          'Earth Science',
          'Environmental Science',
          'Anatomy',
          'Physiology',

          // Social Studies
          'World History',
          'U.S. History',
          'Government',
          'Civics',
          'Economics',
          'Geography',

          // English
          'English 9',
          'English 10',
          'English 11',
          'English 12',
          'Literature',
          'Composition',

          // World Languages
          'Spanish',
          'French',
          'German',
          'Chinese',
          'Latin',

          // Electives
          'Computer Science',
          'Information Technology',
          'Business',
          'Accounting',
          'Marketing',
          'Engineering',
          'Media',
          'Art',
          'Music',
          'Theatre',
          'Design',
          'Automotive',
          'Health Science',
          'Agriculture',
        ],
        grading: {
          letterGrades: [
            { letter: 'A+', range: '97-100%', gpa: 4.0 },
            { letter: 'A', range: '93-96%', gpa: 4.0 },
            { letter: 'A-', range: '90-92%', gpa: 3.7 },
            { letter: 'B+', range: '87-89%', gpa: 3.3 },
            { letter: 'B', range: '83-86%', gpa: 3.0 },
            { letter: 'B-', range: '80-82%', gpa: 2.7 },
            { letter: 'C+', range: '77-79%', gpa: 2.3 },
            { letter: 'C', range: '73-76%', gpa: 2.0 },
            { letter: 'C-', range: '70-72%', gpa: 1.7 },
            { letter: 'D+', range: '67-69%', gpa: 1.3 },
            { letter: 'D', range: '65-66%', gpa: 1.0 },
            { letter: 'F', range: '0-64%', gpa: 0.0 },
          ],
          passing: 'D',
          description: 'Letter grades with GPA on 4.0 scale. D is minimum pass, F is fail.',
        },
      },
      'AP': {
        name: 'Advanced Placement (AP)',
        subjects: [
          // AP Capstone
          'AP Seminar',
          'AP Research',

          // Arts
          'AP 2-D Art & Design',
          'AP 3-D Art & Design',
          'AP Drawing',
          'AP Art History',
          'AP Music Theory',

          // English
          'AP English Language & Composition',
          'AP English Literature & Composition',

          // History & Social Sciences
          'AP African American Studies',
          'AP Comparative Government & Politics',
          'AP European History',
          'AP Human Geography',
          'AP Macroeconomics',
          'AP Microeconomics',
          'AP Psychology',
          'AP U.S. Government & Politics',
          'AP U.S. History',
          'AP World History: Modern',

          // Math & Computer Science
          'AP Calculus AB',
          'AP Calculus BC',
          'AP Computer Science A',
          'AP Computer Science Principles',
          'AP Precalculus',
          'AP Statistics',

          // Sciences
          'AP Biology',
          'AP Chemistry',
          'AP Environmental Science',
          'AP Physics 1',
          'AP Physics 2',
          'AP Physics C: Mechanics',
          'AP Physics C: Electricity & Magnetism',

          // World Languages
          'AP Chinese Language & Culture',
          'AP French Language & Culture',
          'AP German Language & Culture',
          'AP Italian Language & Culture',
          'AP Japanese Language & Culture',
          'AP Latin',
          'AP Spanish Language & Culture',
          'AP Spanish Literature & Culture',
        ],
        grading: {
          letterGrades: [
            { letter: 'A+', range: '97-100%', gpa: 5.0 },
            { letter: 'A', range: '93-96%', gpa: 5.0 },
            { letter: 'A-', range: '90-92%', gpa: 4.7 },
            { letter: 'B+', range: '87-89%', gpa: 4.3 },
            { letter: 'B', range: '83-86%', gpa: 4.0 },
            { letter: 'B-', range: '80-82%', gpa: 3.7 },
            { letter: 'C+', range: '77-79%', gpa: 3.3 },
            { letter: 'C', range: '73-76%', gpa: 3.0 },
            { letter: 'C-', range: '70-72%', gpa: 2.7 },
            { letter: 'D+', range: '67-69%', gpa: 2.3 },
            { letter: 'D', range: '65-66%', gpa: 2.0 },
            { letter: 'F', range: '0-64%', gpa: 0.0 },
          ],
          passing: 'D',
          description: 'Weighted GPA on 5.0 scale for AP courses. AP Exam scores: 5=Extremely well qualified, 4=Well qualified, 3=Qualified, 2=Possibly qualified, 1=No recommendation.',
        },
      },
    },
    grading: {
      letterGrades: [
        { letter: 'A+', range: '97-100%', gpa: 4.0 },
        { letter: 'A', range: '93-96%', gpa: 4.0 },
        { letter: 'A-', range: '90-92%', gpa: 3.7 },
        { letter: 'B+', range: '87-89%', gpa: 3.3 },
        { letter: 'B', range: '83-86%', gpa: 3.0 },
        { letter: 'B-', range: '80-82%', gpa: 2.7 },
        { letter: 'C+', range: '77-79%', gpa: 2.3 },
        { letter: 'C', range: '73-76%', gpa: 2.0 },
        { letter: 'C-', range: '70-72%', gpa: 1.7 },
        { letter: 'D+', range: '67-69%', gpa: 1.3 },
        { letter: 'D', range: '65-66%', gpa: 1.0 },
        { letter: 'F', range: '0-64%', gpa: 0.0 },
      ],
      passing: 'D',
      description: 'Letter grades with GPA on 4.0 scale. D is minimum pass, F is fail.',
    },
  },
};

export const TIMEZONES = [
  'UTC-12:00 - International Date Line West',
  'UTC-11:00 - Midway Island, Samoa',
  'UTC-10:00 - Hawaii',
  'UTC-09:00 - Alaska',
  'UTC-08:00 - Pacific Time (US & Canada)',
  'UTC-07:00 - Mountain Time (US & Canada)',
  'UTC-06:00 - Central Time (US & Canada)',
  'UTC-05:00 - Eastern Time (US & Canada)',
  'UTC-04:00 - Atlantic Time (Canada)',
  'UTC-03:30 - Newfoundland',
  'UTC-03:00 - Brasilia, Buenos Aires',
  'UTC-02:00 - Mid-Atlantic',
  'UTC-01:00 - Azores',
  'UTC+00:00 - London, Dublin, Lisbon',
  'UTC+01:00 - Paris, Berlin, Rome',
  'UTC+02:00 - Athens, Cairo, Jerusalem',
  'UTC+03:00 - Moscow, Baghdad, Nairobi',
  'UTC+03:30 - Tehran',
  'UTC+04:00 - Dubai, Abu Dhabi',
  'UTC+04:30 - Kabul',
  'UTC+05:00 - Karachi, Islamabad',
  'UTC+05:30 - Mumbai, New Delhi',
  'UTC+05:45 - Kathmandu',
  'UTC+06:00 - Dhaka, Almaty',
  'UTC+06:30 - Yangon',
  'UTC+07:00 - Bangkok, Jakarta',
  'UTC+08:00 - Beijing, Hong Kong, Singapore',
  'UTC+09:00 - Tokyo, Seoul',
  'UTC+09:30 - Adelaide',
  'UTC+10:00 - Sydney, Melbourne',
  'UTC+11:00 - Solomon Islands',
  'UTC+12:00 - Auckland, Wellington',
  'UTC+13:00 - Nuku\'alofa',
];
